trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildTest
    steps:
    - task: Docker@2
      displayName: Build test image
      inputs:
        repository: 'dotnetapp'
        command: 'build'
        Dockerfile: 'samples/complexapp/Dockerfile'
        tags: 'test'
        arguments: '--pull --target test'
    - task: Docker@2
      inputs:
        command: 'run'
        arguments: '--name testcontainer dotnetapp:test'
    - task: Docker@2
      inputs:
        command: 'cp'
        arguments: 'testcontainer:/app/tests/TestResults/ ./TestResults'
    - publish: ./TestResults
      name: TestResults
