trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildTest
    steps:
    - task: Docker@2
      displayName: Build test image
      inputs:
        repository: 'dotnetapp'
        command: 'build'
        Dockerfile: 'samples/complexapp/Dockerfile'
        tags: 'test'
        arguments: '--pull --target test'
    - task: Docker@2
      displayName: Run test container
      inputs:
        command: 'run'
        arguments: '--name testcontainer dotnetapp:test'
    - task: Docker@2
      displayName: Copy test results
      inputs:
        command: 'cp'
        arguments: 'testcontainer:/source/tests/TestResults/ ./TestResults'
    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        mergeTestResults: true
        testRunTitle: 'Tests'
    - script: docker rm testcontainer
      displayName: Remove test container
    - task: Docker@2
      displayName: Build runtime image
      inputs:
        containerRegistry: 'devops-with-aks-acr'
        repository: 'dotnetapp'
        command: 'build'
        Dockerfile: 'samples/complexapp/Dockerfile'
        tags: 'AzP-$(Build.BuildId)'
        arguments: '--pull'
    - task: Docker@2
      displayName: Push runtime image
      inputs:
        containerRegistry: 'devops-with-aks-acr'
        repository: 'dotnetapp'
        command: 'push'
        tags: 'AzP-$(Build.BuildId)'